name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        config:
        - Debug
        - Release
        dotnet:
        - 2.1.x
        - 2.2.x
    name: ${{ matrix.os }} ${{ matrix.dotnet }} ${{ matrix.config }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - run: dotnet --info
    - run: env
    #- run: echo 'export DOTNET_ROOT="/opt/hostedtoolcache/dncs/2.1.801/x64/sdk"' >> $BASH_ENV
    - run: env
      env:
        DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.1.801/x64/sdk
    - name: Test Coverage
      run: ./coverage.sh netcoreapp2.1 ${{ matrix.config }}
      env:
        DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.1.801/x64/sdk
